from contextlib import contextmanager
from http.cookiejar import request_port

import psycopg2
import os
from dotenv import load_dotenv

from database.entities.UniversityEntity import UniversityEntity
from database.repositories.UniversityRepository import UniversityRepository

load_dotenv()
user = os.getenv("DB_USER")
password = os.getenv("DB_PASS")
host = os.getenv("DB_HOST")
port = os.getenv("DB_PORT")


class UniversitiesService:
    def __init__(self) -> None:
        self.__connection = psycopg2.connect(
            dbname="max_universities",
            user=user,
            password=password,
            host=host,
            port=port,
        )
        self.__university_repo = UniversityRepository()
        self.__initializate_database()

    @contextmanager
    def __transaction(self):
        """Контекстный менеджер для безопасных транзакций"""
        try:
            yield
            self.__connection.commit()
        except Exception as e:
            self.__connection.rollback()
            raise e
    
    def get_uni(self, university_id: int) -> UniversityEntity | None:
        with self.__transaction():
            with self.__connection.cursor() as cursor:
                return self.__university_repo.get_university(cursor, university_id)

    def get_uni_by_name(self, university_name: str) -> UniversityEntity | None:
        with self.__transaction():
            with self.__connection.cursor() as cursor:
                return self.__university_repo.get_university_by_name(cursor, university_name)

    def create_uni(self, university: UniversityEntity) -> int:
        with self.__transaction():
            with self.__connection.cursor() as cursor:
                return self.__university_repo.create_university(cursor, university)

    def find_uni(self, query: str) -> list[UniversityEntity]:
        with self.__transaction():
            with self.__connection.cursor() as cursor:
                return self.__university_repo.search(cursor, query)
            
    def __initializate_database(self):
        with self.__transaction():
            with self.__connection.cursor() as cursor:
                cursor.execute("""
                   CREATE TABLE IF NOT EXISTS  university (
                    id INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
                    name VARCHAR(255)
                    );
                """)
                cursor.execute("CREATE EXTENSION IF NOT EXISTS pg_trgm")
